apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guts
  name: guts
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guts
  template:
    metadata:
      labels:
        app: guts
    spec:
      containers:
      - image: gcr.io/guts-341516/guts
        imagePullPolicy: IfNotPresent
        name: guts
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi