apiVersion: v1
kind: Service
metadata:
  labels:
    app: guts
  name: guts
  namespace: sandbox
spec:
  ports:
  - name: http
    port: 4111
    protocol: TCP
    targetPort: 3111
    nodePort: 30001
  selector:
    app: guts
  sessionAffinity: None
  type: NodePort
